[package]
name = "px-store"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow.workspace = true
reqwest.workspace = true
sha2.workspace = true
tempfile.workspace = true
hex.workspace = true
serde.workspace = true
serde_json.workspace = true
