[package]
name = "px-resolver"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow.workspace = true
indexmap.workspace = true
pep440_rs.workspace = true
serde.workspace = true
serde_json.workspace = true
reqwest.workspace = true
pep508_rs = "0.5"
